name: ESLint Check

on: [pull_request]

jobs:
  build:
    name: ESLint Verify
    runs-on: ubuntu-latest

  steps:
    - name: Deploying Project
    - uses: integrtr/ui5-deploy@master
      with:
        type: 'bsp'
        user: ${{ secrets.ABAP_USER }}
        password: ${{ secrets.ABAP_PASSWORD }}
        host: ${{ secrets.ABAP_HOST }}
